version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - zip deployment_package.zip index.js
      - aws lambda update-function-code --function-name hello_lambda --zip-file fileb://deployment_package.zip
artifacts:
  files:
    - deployment_package.zip
