version: 0.2
phases:
  build:
    commands:
      - echo "Building the project..."
      - zip deployment_package.zip index.js
      - aws lambda update-function-code --function-name helloworldfromlambda --zip-file fileb://deployment_package.zip
